server:
  port: 9091
  servlet:
    context-path: /admin
  forward-headers-strategy: framework


spring:
  application:
    name: admin-server
  boot:
    admin:
      client:
        # You can leave this empty if the server isn't acting as a client
        url: http://admin-server:9091
      context-path: /admin



---
spring:
  config:
    activate:
      on-profile: docker

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/eureka/
