server:
  port: 9091
  # servlet:
  #   context-path: /admin
    
---
spring:
  config:
    activate:
      on-profile: docker
      
  application:
    name: admin-server
  boot:
    admin:
      ui:
        public-url: http://35.244.33.210:30640/admin
      context-path: /admin
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
        allowed-headers: "*"



eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/eureka/
  instance:
    prefer-ip-address: false
    hostname: admin-server
    non-secure-port: 9091
