server:
  port: 9091
  servlet:
    context-path: /admin

---
spring:
  config:
    activate:
      on-profile: docker
      
  # application:
  #   name: admin-server
  # boot:
  #   admin:
  #     # Enabling Spring Boot Admin Server
  #     adminServer:
  #       enabled: true
  #     client:
  #          #You can leave this empty if the server isn't acting as a client
  #       url: http://admin-server:9091
  #     context-path: /admin 


  application:
    name: admin-server
  boot:
    admin:
      ui:
        public-url: http://34.93.136.175:31081/admin
        instance:
          service-base-url: http://admin-server:9091
      context-path: /admin
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
        allowed-headers: "*"
        

  # cloud:
  #   config:
  #     enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/eureka/
  instance:
    prefer-ip-address: false
    hostname: admin-server
    non-secure-port: 9091
