server:
  port: 9091
  servlet:
    context-path: /admin


---
spring:
  config:
    activate:
      on-profile: docker

  application:
    name: admin-server

  boot:
    admin:
      context-path: /admin
      adminServer:
        enabled: true
      client:
        url: http://admin-server:9091

  cloud:
    config:
      enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
