spring:
  config:
    activate:
      on-profile: default
eureka:
  instance:
    # enable to register multiple app instances with a random server port
    instance-id: ${spring.application.name}:${random.uuid}

---
spring:
  config:
    activate:
      on-profile: docker
server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
management:
  zipkin:
    tracing:
      endpoint: http://tracing-server:9411/api/v2/spans

  boot:
    admin:
      client:
        url: http://admin-server:9091
        instance:
          prefer-ip: true
          service-base-url: http://api-gateway:8080/api/customers
