# ﻿server:
#   port: 8761
#   servlet:
#     context-path: /eureka

# eureka:
#   client:
#     registerWithEureka: false
#     fetchRegistry: false
#   server:
#     maxThreadsForPeerReplication: 0

server:
  port: 8761
  servlet:
    context-path: /eureka-service

eureka:
  dashboard:
    enabled: true
    path: /  # Dashboard at root of context path
  client:
    register-with-eureka: false
    fetch-registry: false

spring:
  web:
    resources:
      static-locations: classpath:/eureka/  # Specific to Eureka's resource location
      add-mappings: true
  mvc:
    static-path-pattern: /eureka-service/**
