server:
  port: 8761
  servlet:
    context-path: /eureka

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    maxThreadsForPeerReplication: 0

spring:
  security:
    user:
      name: eureka
      password: eureka

