# ﻿server:
#   port: 8761
#   servlet:
#     context-path: /eureka

# eureka:
#   client:
#     registerWithEureka: false
#     fetchRegistry: false
#   server:
#     maxThreadsForPeerReplication: 0

server:
  port: 8761
  servlet:
    context-path: /eureka-service  # Custom base path

eureka:
  dashboard:
    path: /  # Dashboard at /eureka-service/
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka-service/  # Single path element

spring:
  web:
    resources:
      static-locations: classpath:/static/
